/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UEFA_Package;

/**
 *
 * @author ìmítâtôr
 */
public class view_frame extends javax.swing.JFrame {

    /**
     * Creates new form view_frame
     */
    public view_frame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentpanel = new javax.swing.JPanel();
        yearpanel = new javax.swing.JPanel();
        y19 = new javax.swing.JLabel();
        y18 = new javax.swing.JLabel();
        y17 = new javax.swing.JLabel();
        y16 = new javax.swing.JLabel();
        y15 = new javax.swing.JLabel();
        y14 = new javax.swing.JLabel();
        y13 = new javax.swing.JLabel();
        y12 = new javax.swing.JLabel();
        y11 = new javax.swing.JLabel();
        y10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        backlabel = new javax.swing.JLabel();
        bglabel = new javax.swing.JLabel();
        y19panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bglabel2 = new javax.swing.JLabel();
        y18panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        bglabel3 = new javax.swing.JLabel();
        y17panel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        bglabel4 = new javax.swing.JLabel();
        y16panel = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        bglabel5 = new javax.swing.JLabel();
        y15panel = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        bglabel6 = new javax.swing.JLabel();
        y14panel = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        bglabel7 = new javax.swing.JLabel();
        y13panel = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        bglabel8 = new javax.swing.JLabel();
        y12panel = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        bglabel9 = new javax.swing.JLabel();
        y11panel = new javax.swing.JPanel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        bglabel10 = new javax.swing.JLabel();
        y10panel = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        bglabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STATS ( UEFA )");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        parentpanel.setLayout(new java.awt.CardLayout());

        yearpanel.setOpaque(false);
        yearpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        y19.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y19.setForeground(new java.awt.Color(255, 255, 255));
        y19.setText("2019 - 20");
        y19.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y19MouseClicked(evt);
            }
        });
        yearpanel.add(y19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 40));

        y18.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y18.setForeground(new java.awt.Color(255, 255, 255));
        y18.setText("2018 - 19");
        y18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y18MouseClicked(evt);
            }
        });
        yearpanel.add(y18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 140, 40));

        y17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y17.setForeground(new java.awt.Color(255, 255, 255));
        y17.setText("2017 - 18");
        y17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y17MouseClicked(evt);
            }
        });
        yearpanel.add(y17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 130, 40));

        y16.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y16.setForeground(new java.awt.Color(255, 255, 255));
        y16.setText("2016 - 17");
        y16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y16MouseClicked(evt);
            }
        });
        yearpanel.add(y16, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 130, 40));

        y15.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y15.setForeground(new java.awt.Color(255, 255, 255));
        y15.setText("2015 - 16");
        y15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y15MouseClicked(evt);
            }
        });
        yearpanel.add(y15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 40));

        y14.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y14.setForeground(new java.awt.Color(255, 255, 255));
        y14.setText("2014 - 15");
        y14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y14MouseClicked(evt);
            }
        });
        yearpanel.add(y14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 130, 40));

        y13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y13.setForeground(new java.awt.Color(255, 255, 255));
        y13.setText("2013 - 14");
        y13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y13MouseClicked(evt);
            }
        });
        yearpanel.add(y13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 130, 40));

        y12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y12.setForeground(new java.awt.Color(255, 255, 255));
        y12.setText("2012 - 13");
        y12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y12MouseClicked(evt);
            }
        });
        yearpanel.add(y12, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, 130, 40));

        y11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y11.setForeground(new java.awt.Color(255, 255, 255));
        y11.setText("2011 - 12");
        y11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y11MouseClicked(evt);
            }
        });
        yearpanel.add(y11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 130, 40));

        y10.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        y10.setForeground(new java.awt.Color(255, 255, 255));
        y10.setText("2010 -  11");
        y10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        y10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y10MouseClicked(evt);
            }
        });
        yearpanel.add(y10, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 130, 40));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("STATISTICS");
        yearpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 360, 70));

        jLabel92.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        jLabel92.setForeground(new java.awt.Color(240, 240, 240));
        jLabel92.setText("( Last 10 years )");
        yearpanel.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 160, 30));

        backlabel.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        backlabel.setForeground(new java.awt.Color(255, 255, 255));
        backlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backlabel.setText("<- Back");
        backlabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backlabel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        backlabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backlabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backlabelMouseEntered(evt);
            }
        });
        yearpanel.add(backlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        bglabel.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        bglabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/Bground.jpg"))); // NOI18N
        bglabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        bglabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yearpanel.add(bglabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(yearpanel, "card2");

        y19panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y19panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<- Back");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        y19panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/bayern_ico.png"))); // NOI18N
        y19panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 210, 200));

        jLabel7.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FC Bayern München ");
        y19panel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2019stats_1.png"))); // NOI18N
        y19panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel9.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 153, 255));
        jLabel9.setText("2019/20  SEASON");
        y19panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2019stats_2.png"))); // NOI18N
        y19panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 340, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2019stats_3.png"))); // NOI18N
        y19panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 480, 70));

        jLabel12.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 153, 255));
        jLabel12.setText("Final");
        y19panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel13.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 153, 255));
        jLabel13.setText(".......... Winner ...........");
        y19panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/19winnerbg.png"))); // NOI18N
        y19panel.add(bglabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        parentpanel.add(y19panel, "card4");

        y18panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y18panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<- Back");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        y18panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LIVERPOOL");
        y18panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 441, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/liverpool_ico.png"))); // NOI18N
        y18panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 190));

        jLabel14.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 153, 255));
        jLabel14.setText("2018/19  SEASON");
        y18panel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2018stats_2.png"))); // NOI18N
        y18panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2018stat_1.png"))); // NOI18N
        y18panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2018stat_3.png"))); // NOI18N
        y18panel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel18.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setText("Final");
        y18panel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel19.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 153, 255));
        jLabel19.setText(".......... Winner ...........");
        y18panel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/18winnerbg.png"))); // NOI18N
        y18panel.add(bglabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y18panel, "card5");

        y17panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y17panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("<- Back");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        y17panel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("REAL  MADRID");
        y17panel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, 50));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/madrid_logo.png"))); // NOI18N
        y17panel.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 110, 150));

        jLabel23.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 255));
        jLabel23.setText("2017/18  SEASON");
        y17panel.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2017stats_2.png"))); // NOI18N
        y17panel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2017stats_1.png"))); // NOI18N
        y17panel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2017stats_3.png"))); // NOI18N
        y17panel.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel27.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 153, 255));
        jLabel27.setText("Final");
        y17panel.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel28.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 153, 255));
        jLabel28.setText(".......... Winner ...........");
        y17panel.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/17winnerbg.png"))); // NOI18N
        y17panel.add(bglabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y17panel, "card5");

        y16panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y16panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("<- Back");
        jLabel29.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        y16panel.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("REAL  MADRID");
        y16panel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, 50));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/madrid_logo.png"))); // NOI18N
        y16panel.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 150));

        jLabel32.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 153, 255));
        jLabel32.setText("2016/17  SEASON");
        y16panel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2016stats_2.png"))); // NOI18N
        y16panel.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2016stats_1.png"))); // NOI18N
        y16panel.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2016stats_3.png"))); // NOI18N
        y16panel.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel36.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(51, 153, 255));
        jLabel36.setText("Final");
        y16panel.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel37.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(51, 153, 255));
        jLabel37.setText(".......... Winner ...........");
        y16panel.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/16winnerbg.png"))); // NOI18N
        y16panel.add(bglabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y16panel, "card5");

        y15panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y15panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("<- Back");
        jLabel38.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        y15panel.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel39.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("REAL  MADRID");
        y15panel.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, 50));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/madrid_logo.png"))); // NOI18N
        y15panel.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 160));

        jLabel41.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 153, 255));
        jLabel41.setText("2015/16  SEASON");
        y15panel.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2015stats_2.png"))); // NOI18N
        y15panel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2015stats_1.png"))); // NOI18N
        y15panel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2015stats_3.png"))); // NOI18N
        y15panel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 480, 80));

        jLabel45.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(51, 153, 255));
        jLabel45.setText("Final");
        y15panel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel46.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(51, 153, 255));
        jLabel46.setText(".......... Winner ...........");
        y15panel.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/15winnerbg.png"))); // NOI18N
        y15panel.add(bglabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y15panel, "card5");

        y14panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y14panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("<- Back");
        jLabel47.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        y14panel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel48.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(255, 255, 255));
        jLabel48.setText("FC  BARCELONA");
        y14panel.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, 50));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/Barca_logo.png"))); // NOI18N
        y14panel.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, 120));

        jLabel50.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(51, 153, 255));
        jLabel50.setText("2014/15  SEASON");
        y14panel.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2014stats_2.png"))); // NOI18N
        y14panel.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2014stats_1.png"))); // NOI18N
        y14panel.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2014stats_3.png"))); // NOI18N
        y14panel.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel54.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 153, 255));
        jLabel54.setText("Final");
        y14panel.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel55.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(51, 153, 255));
        jLabel55.setText(".......... Winner ...........");
        y14panel.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/14winnerbg.png"))); // NOI18N
        y14panel.add(bglabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y14panel, "card5");

        y13panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y13panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("<- Back");
        jLabel56.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel56MouseClicked(evt);
            }
        });
        y13panel.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel57.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("REAL  MADRID");
        y13panel.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, 50));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/madrid_logo.png"))); // NOI18N
        y13panel.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, 150));

        jLabel59.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(51, 153, 255));
        jLabel59.setText("2013/14  SEASON");
        y13panel.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2013stats_2.png"))); // NOI18N
        y13panel.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2013stats_1.png"))); // NOI18N
        y13panel.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2013stats_3.png"))); // NOI18N
        y13panel.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 480, 80));

        jLabel63.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel63.setForeground(new java.awt.Color(51, 153, 255));
        jLabel63.setText("Final");
        y13panel.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel64.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(51, 153, 255));
        jLabel64.setText(".......... Winner ...........");
        y13panel.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/13winnerbg.png"))); // NOI18N
        y13panel.add(bglabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y13panel, "card5");

        y12panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y12panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel65.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel65.setForeground(new java.awt.Color(255, 255, 255));
        jLabel65.setText("<- Back");
        jLabel65.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel65MouseClicked(evt);
            }
        });
        y12panel.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel66.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(255, 255, 255));
        jLabel66.setText("FC Bayern München ");
        y12panel.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, 50));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/bayern_ico.png"))); // NOI18N
        y12panel.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 200, 200));

        jLabel68.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(51, 153, 255));
        jLabel68.setText("2012/13  SEASON");
        y12panel.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2012stats_2.png"))); // NOI18N
        y12panel.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 300, -1));

        jLabel70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2012stats_1.png"))); // NOI18N
        y12panel.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2012stats_3.png"))); // NOI18N
        y12panel.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel72.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(51, 153, 255));
        jLabel72.setText("Final");
        y12panel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel73.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(51, 153, 255));
        jLabel73.setText(".......... Winner ...........");
        y12panel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/12winnerbg.png"))); // NOI18N
        y12panel.add(bglabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y12panel, "card5");

        y11panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y11panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel74.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(255, 255, 255));
        jLabel74.setText("<- Back");
        jLabel74.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel74MouseClicked(evt);
            }
        });
        y11panel.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel75.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel75.setForeground(new java.awt.Color(255, 255, 255));
        jLabel75.setText("CHELSEA");
        y11panel.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, 50));

        jLabel76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/chelsea_logo.png"))); // NOI18N
        y11panel.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 120, 120));

        jLabel77.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(51, 153, 255));
        jLabel77.setText("2011/12  SEASON");
        y11panel.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2011stats_2.png"))); // NOI18N
        y11panel.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2011stats_1.png"))); // NOI18N
        y11panel.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2011stats_3.png"))); // NOI18N
        y11panel.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 90));

        jLabel81.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel81.setForeground(new java.awt.Color(51, 153, 255));
        jLabel81.setText("Final");
        y11panel.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel82.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel82.setForeground(new java.awt.Color(51, 153, 255));
        jLabel82.setText(".......... Winner ...........");
        y11panel.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/11winnerbg.png"))); // NOI18N
        bglabel10.setToolTipText("");
        y11panel.add(bglabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y11panel, "card5");

        y10panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 3));
        y10panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel83.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        jLabel83.setForeground(new java.awt.Color(255, 255, 255));
        jLabel83.setText("<- Back");
        jLabel83.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel83MouseClicked(evt);
            }
        });
        y10panel.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel84.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        jLabel84.setForeground(new java.awt.Color(255, 255, 255));
        jLabel84.setText("FC BARCELONA ");
        y10panel.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, 50));

        jLabel85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/Barca_logo.png"))); // NOI18N
        y10panel.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, 120));

        jLabel86.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(51, 153, 255));
        jLabel86.setText("2010/11  SEASON");
        y10panel.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 490, 80));

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2010stats_2.png"))); // NOI18N
        y10panel.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2010stats_1.png"))); // NOI18N
        y10panel.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 120, 300, -1));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/2010stats_3.png"))); // NOI18N
        y10panel.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 480, 70));

        jLabel90.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        jLabel90.setForeground(new java.awt.Color(51, 153, 255));
        jLabel90.setText("Final");
        y10panel.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 110, -1));

        jLabel91.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        jLabel91.setForeground(new java.awt.Color(51, 153, 255));
        jLabel91.setText(".......... Winner ...........");
        y10panel.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 370, -1));

        bglabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UEFA_Package/10winnerbg.png"))); // NOI18N
        y10panel.add(bglabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 630));

        parentpanel.add(y10panel, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backlabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseClicked
 new UEFA_FRAME().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backlabelMouseClicked

    private void backlabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backlabelMouseEntered

    }//GEN-LAST:event_backlabelMouseEntered

    private void y19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y19MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y19panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y19MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void y18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y18MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y18panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel38MouseClicked

    private void y17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y17MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y17panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y17MouseClicked

    private void y16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y16MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y16panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y16MouseClicked

    private void y15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y15MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y15panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y15MouseClicked

    private void y14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y14MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y14panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y14MouseClicked

    private void y13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y13MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y13panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y13MouseClicked

    private void y12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y12MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y12panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y12MouseClicked

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel47MouseClicked

    private void jLabel56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel56MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel56MouseClicked

    private void jLabel65MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel65MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel65MouseClicked

    private void jLabel74MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel74MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel74MouseClicked

    private void jLabel83MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel83MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(yearpanel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_jLabel83MouseClicked

    private void y11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y11MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y11panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y11MouseClicked

    private void y10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y10MouseClicked
        // TODO add your handling code here:
        parentpanel.removeAll();
        parentpanel.add(y10panel);
        parentpanel.repaint();
        parentpanel.revalidate();
    }//GEN-LAST:event_y10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backlabel;
    private javax.swing.JLabel bglabel;
    private javax.swing.JLabel bglabel10;
    private javax.swing.JLabel bglabel11;
    private javax.swing.JLabel bglabel2;
    private javax.swing.JLabel bglabel3;
    private javax.swing.JLabel bglabel4;
    private javax.swing.JLabel bglabel5;
    private javax.swing.JLabel bglabel6;
    private javax.swing.JLabel bglabel7;
    private javax.swing.JLabel bglabel8;
    private javax.swing.JLabel bglabel9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel parentpanel;
    private javax.swing.JLabel y10;
    private javax.swing.JPanel y10panel;
    private javax.swing.JLabel y11;
    private javax.swing.JPanel y11panel;
    private javax.swing.JLabel y12;
    private javax.swing.JPanel y12panel;
    private javax.swing.JLabel y13;
    private javax.swing.JPanel y13panel;
    private javax.swing.JLabel y14;
    private javax.swing.JPanel y14panel;
    private javax.swing.JLabel y15;
    private javax.swing.JPanel y15panel;
    private javax.swing.JLabel y16;
    private javax.swing.JPanel y16panel;
    private javax.swing.JLabel y17;
    private javax.swing.JPanel y17panel;
    private javax.swing.JLabel y18;
    private javax.swing.JPanel y18panel;
    private javax.swing.JLabel y19;
    private javax.swing.JPanel y19panel;
    private javax.swing.JPanel yearpanel;
    // End of variables declaration//GEN-END:variables
}
